# Generated by Django 4.1.5 on 2023-01-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuessNumbers',
            new_name='GuessNumberss',
        ),
    ]
